### ISSUE TITLE
Support HDR switches (MQM8790-HS2F)

### ISSUE THREAD

**Issue by guilbaults** [guilbaults/check_ib_switch#1]
The subcommands --psu and --temp are currently broken:
```
python3 check_ib_switch.py --guid changeme --psu
Traceback (most recent call last):
  File "check_ib_switch.py", line 182, in <module>
    if psus[psu_watt] < 30:
KeyError: 'watt_0'
python3 check_ib_switch.py --guid changeme--temp
Traceback (most recent call last):
  File "check_ib_switch.py", line 212, in <module>
    temperature = temp_info['temperature']/10
KeyError: 'temperature'
```

The --fan command do works:
```
# python3 check_ib_switch.py --guid changeme --fan
Switch OK | Fan1_RPM=12027;;4500:13000;; Fan2_RPM=10846;;4500:13000;; Fan3_RPM=11813;;4500:13000;; Fan4_RPM=10846;;4500:13000;; Fan5_RPM=12027;;4500:13000;; Fan6_RPM=10846;;4500:13000;; Fan7_RPM=12137;;4500:13000;; Fan8_RPM=10935;;4500:13000;;
GUID=changeme LID=737 Name=changeme
Jaguar UnmngIB200 PN=MQM8790-HS2F Rev=AF SN=changeme
```

**Comment by guilbaults** [comment]
Solved in 40edc3d201d86966e22c02b5b2145800b0a96954
